//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ak_Bars_Galeryyy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ak_Bars_GalleryyyEntities : DbContext
    {
        public Ak_Bars_GalleryyyEntities()
            : base("name=Ak_Bars_GalleryyyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Buy> Buys { get; set; }
        public virtual DbSet<Exibit> Exibits { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Lvl> Lvls { get; set; }
        public virtual DbSet<Newcollection> Newcollections { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserExibit> UserExibits { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
