//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ak_Bars_Galeryyy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int Buy_Id { get; set; }
        public int Name_Id { get; set; }
        public int Price_Id { get; set; }
        public string Phone { get; set; }
        public string RealName { get; set; }
    
        public virtual Newcollection Newcollection { get; set; }
    }
}
