//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ak_Bars_Galeryyy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExibit
    {
        public int UserExibit_Id { get; set; }
        public int User_Id { get; set; }
        public int Exibit_Id { get; set; }
    
        public virtual Exibit Exibit { get; set; }
        public virtual User User { get; set; }
    }
}
